// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/23 17:05:51
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Code/Project/Github/ContentForest/content-forest-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/plugins/**/*.{js,ts,mjs}","D:/Code/Project/Github/ContentForest/content-forest-front/composables/**/*.{js,ts,mjs}","D:/Code/Project/Github/ContentForest/content-forest-front/utils/**/*.{js,ts,mjs}","D:/Code/Project/Github/ContentForest/content-forest-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Code/Project/Github/ContentForest/content-forest-front/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;